### PR TITLE
Add support for recvport_drop

### PR DESCRIPTION
**Pull request by HenryHeffan**

### CODE REVIEW

**Comment by HenryHeffan** [comment]
@rmanohar this allows for better generation of code for a receive without a associated variable, so we no longer need to create a temporary variable for this. Is this correct, im fairly sure the qdi one is, but am less confidant in the bdopt one

**Comment by rmanohar** [comment]
Makes sense. 

There is a modification needed for the QDI version---the control request needs to be combined with the validity tree to generate the ack. The simplest change would be: (a) removing  the sigbuf (the large fanout on `cr` no longer exists; (b) adding an inverter from `c.r` to `cr`; and (c) adding `cr` to the completion tree (so `W+1` size tree) using `{cr} # _v` for array concatenation.

There is also a modification needed for the BD version, since there's no longer a `port` channel. The inverter `INVX1`'s output should be `c.a` (not `port.r`), and `ch.a` can be connected to `c.a`.

**Comment by HenryHeffan** [comment]
@rmanohar  I think I fixed the QDI version. I also added another cell for QDI which is a "bitslice". It is like the widthconv except it can extract bits from the middle of an expression

**Comment by rmanohar** [comment]
The fixes look good! One last comment, and I can merge this in. There's already a "bitfield" process that can do the same thing as bitslice; I think `bitslice<W1,LSB,MSB,W2>` is `bitfield<W1,LSB,MSB>`... do we need this, or can we implement bitslice using bitfield so as to avoid replicating the same circuit?

**Comment by HenryHeffan** [comment]
I missed the bitfield gate. I can use that instead!

**Pull request merged**
